### ISSUE TITLE
Is there a way to get this to use .mdlrc? 

### ISSUE THREAD

**Issue by rshade** [DavidAnson/vscode-markdownlint#105]
I am trying to standardize markdown lint across code editors and ci, it seems that mdl uses one config and markdownlint uses another, is there a per editor change I can do to use .mdlrc? or any other suggestions?

**Comment by DavidAnson** [comment]
If you want the best compatibility between this extension and a CLI, you’ll have the easiest time using the markdownlint CLI written in/for Node.js: https://github.com/igorshubovych/markdownlint-cli

This extension and that CLI use the same core library implementation and share the same configuration file, `.markdownlint.json`.

The `mdl` CLI predates this one and was written in Ruby. The configuration file format it uses is not supported by either of the Node implementations. Furthermore, the set of rules has diverged somewhat over time and there are one or two places where we have made different decisions about a shared rule.

It would be possible to add support for the `.mdlrc` format to this extension, but that would only be a partial solution because of the differences I’ve just outlined.

**Comment by rshade** [comment]
@DavidAnson awesome thank you. That is good to know, makes total sense.
