### ISSUE TITLE
Doesn't support c#?

### ISSUE THREAD

**Issue by ngzhio** [DavidAnson/vscode-markdownlint#112]
No matter I add `cs`, `csharp`, or `c#` after code fences, it reports a problem [MD046 - Code block style](https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md#md046).

**Comment by DavidAnson** [comment]
Please provide an example of this not working as you expect. Is there any chance you are confusing rule MD040 with rule MD046? The rule you say is failing is about consistency within the document rather than whether a language is provided on the code fence.

Here is an example of this scenario you describe working without a violation: https://dlaa.me/markdownlint/#%25m%23%20Issue%20112%0A%0AHere%20is%20a%20code%20fence%3A%0A%0A%60%60%60csharp%0Avar%20x%20%3D%205%3B%0A%60%60%60%0A

**Comment by ngzhio** [comment]
Example:

<img width="811" alt="屏幕快照 2020-04-20 上午11 10 31" src="https://user-images.githubusercontent.com/63144665/79710451-9665ac00-82f7-11ea-80c0-57335fd77ba0.png">

**Comment by nschonni** [comment]
Since the default is "consistent", you've likely got an "indented" style codeblock above, so it's flagging the "fenced" style it saw after an "indented" style block.
Explicitly set the rule to "fenced" and it will flag your earlier "indented style block.

**Comment by ngzhio** [comment]
> Since the default is "consistent", you've likely got an "indented" style codeblock above, so it's flagging the "fenced" style it saw after an "indented" style block.
> Explicitly set the rule to "fenced" and it will flag your earlier "indented" style block.

Yes, I wrote an "indented" style code block above. You mean we can't mix these two code styles on the same file? It's very inconvenient!

**Comment by nschonni** [comment]
If you don't like the rule, you can just set it to "false" in your config to turn it off. This really isn't about the library not supporting "c#", but a misunderstanding about the default configuration

**Comment by DavidAnson** [comment]
Right, this rule exists to help maintain a consistent style for code blocks within a file, either indented or fenced. If you want to use both in the same file, then you’ll want to disable this rule.

**Comment by ngzhio** [comment]
I got it. Thanks.
