### ISSUE TITLE
Idea: Delay linting specific rules

### ISSUE THREAD

**Issue by Strepto** [DavidAnson/vscode-markdownlint#118]
User Story: As a writer, I want to finish my current line of thought before the linter complains, so that I can focus on my writing instead of the linter.

Some linting such as MD009 Trailing Whitespace, is invasive while writing a sentence, but can be good to clean up when saving.

Others such as correcting link and whitespace around lists are good to have while writing, as it makes me understand how and what I should format my lists and tables without having to check by saving each time.

I would like a setting that ignores specific rules until save, or a smarter system of delaying certain rules until the line is committed (ie by moving the cursor to a different line or similar)

**Comment by DavidAnson** [comment]
Here’s how to configure the linter to only run when you save the document: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintrun

**Comment by Strepto** [comment]
I am more interested in having a select linting options delayed, such as MD009 not appearing when I have my cursor in place to enter the next word and wait for 500ms to find a good word to use. It might just be me being slow, but I find some of these errors appear way too early and with no context sensitivity to my "ongoing" actions.

Example where I would like some context sensitivity: 
![https://i.imgur.com/ipurBNK.gif](https://i.imgur.com/ipurBNK.gif)

I think the addon is great, and it helps me being consistent. I like the realtime feedback for almost all the features, but there are some that makes me just a tad bit distracted :D

**Comment by DavidAnson** [comment]
OK. I think I get it. Do you feel that the list of special rules would need to be configurable, or is it pretty much just MD009 that’s problematic? What if MD009 only ran when you saved the document (but everything else ran on the current brief delay), would that be helpful?

**Comment by Strepto** [comment]
I think that would be the most important one yes :)

But also such as these popping up when I am clearly starting a new list element, is kind of flow breaking. 
![image](https://user-images.githubusercontent.com/3185998/83171613-a8b4e000-a116-11ea-8258-88413452649c.png)

So the my dream feature would be to have some kind of cursor context aware linting. But MD009 is the most frequent one, and running that on save would be a great improvement to writing flow.

**Comment by orionlee** [comment]
For me , `MD032` is the one that sends false alarms most often, in the case similar to the screenshot above, when I am composing my thoughts and has not yet typed anything in the new bullet item.

For `MD032`, if the rule can be tweaked so that if the cursor is a blank bullet line, it will not fire the warning (in onType mode).

**Comment by orionlee** [comment]
For `MD009`, one way to address @Strepto 's use case without any code changes is to disable the rule altoghether, and use vscode's built-in settings to trim trailing whitespaces on save.

![image](https://user-images.githubusercontent.com/250644/90679149-9e394c80-e214-11ea-81be-5ec33bdf4cd5.png)

**Comment by JTBrinkmann** [comment]
I also often get distracted because of these "premature" warnings. Specifically MD009, MD012, MD022, MD026, MD047 are annoying while writing.

Maybe ignoring the current line would help instead of / in addition to a delay. Or ignoring new warnings that touch the current cursor position (at the time of linting, if there's a delay), because the "current line" might be too broad.

**Comment by rainersigwald** [comment]
I would also like an "ignore warnings involving the current cursor position" setting, for reasons like others here: I know I need a new paragraph/list item/word, but I need to think about it.

**Comment by DavidAnson** [comment]
Okay, first, good news! Second, I'd like to keep this simple like now instead of having to support a complicated table of exclusions and delays. One idea I had was to allow the focusMode value to be a number N which would mean "hide violations within N lines of the cursor". In this case, the value 1 would work for your scenario, but I'd guess 0 (like today) works for most people?

**Comment by orionlee** [comment]
> One idea I had was to allow the focusMode value to be a number N which would mean "hide violations within N lines of the cursor". In this case, the value 1 would work for your scenario, but I'd guess 0 (like today) works for most people?

That sounds quite reasonable!

I can't speak for others, but I think anyone who writes down lots of list items in markdown would face the issue, unless they disable `MD032`.
