### ISSUE TITLE
MD013 disabled by default?

### ISSUE THREAD

**Issue by goldcaddy77** [DavidAnson/vscode-markdownlint#12]
Why is rule `MD013` disabled by default?  Is setting a max line length in markdown an anti-pattern?

**Comment by DavidAnson** [comment]
The line-length check is disabled by default because there are many files that violate the default 80 character rule and there isn't really a standard for line-length across projects. Rather than have people see multiple warnings every time they open a file (and get annoyed), I choose to disable this rule by default in the editing experience. Unlike most of the other rules, line length is not about correctness, but rather about convention, so it seemed like a reasonable trade-off.

**Comment by goldcaddy77** [comment]
First, thanks for the extension!  I appreciate the hard work.

Re: line length, the reason I ask is because it made it seem like the tool wasn't working until I determined that there was a default config.  IMO you're opting into the `markdownlint` ecosystem, so you should opt into it all of the rules and override the `MD013` setting if you disagree.  Just my 2 cents.  :)

**Comment by DavidAnson** [comment]
If you enable this rule in your user configuration, it will be applied by default when you open a new folder. I appreciate your suggestion, but am inclined to keep the current behavior for now. Thank you again!
