### ISSUE TITLE
MD012 - multiple blank lines serve no purpose?

### ISSUE THREAD

**Issue by pepoluan** [DavidAnson/vscode-markdownlint#126]
I have issue with the rationale of this rule, which I quote in full below (emphasis mine):

> Except in a code block, blank lines **serve no purpose** and do not affect the rendering of content.

To quote your own README (emphasis mine):

> The Markdown markup language is designed to be **easy to read**

Additional blank lines creates a **visual gap**, helping humans to perform "visual grouping", and thus _very_ helpful to quickly form a logical "hierarchy" of the text in the readers' mind. This _greatly_ helps with **readability** (of the 'raw' markdown, not the rendered result, of course).

Besides, if multiple blank lines "do not affect the rendering of content", there really is no urgency nor _need_ to flag this.

I suggest defaulting this lint rule to `false`, or even taking it out altogether; I think you will end up with a more concise code (after all, you already have to cater for some exclusions such as "will not be triggered ... inside code blocks" -- taking out this rule means you no longer have to detect whether blank lines happen within code blocks or outside of).

**Comment by DavidAnson** [comment]
These are good points and we could have similar discussions about many of the other built-in rules. In this case, the rule helps enforce consistency within a document and that is something I feel is valuable. My documents use one blank line everywhere and if I accidentally introduced two or three, I would consider that a mistake and want to be informed of it so I could correct it. That is something this rule can do. If you prefer two or three spaces or just disagree with the rule, you can configure or disable it accordingly. By convention, rules are enabled by default because it's easier to identify the issues in the document and decide what to fix or disable that way. If everything started disabled, I think people would have a harder time choosing what to enable. I try to keep very controversial rules out of the core library, but this is one of the original set inherited from Ruby and although it is more stylistic, I think the pattern it enforces is used fairly broadly. I am adding a note for myself to do some analysis here across the ecosystem, but for the time being I am not inclined to change the default configuration.

**Comment by DavidAnson** [comment]
MD012 looks to be disabled about 5% of the time. That is not very often, so I plan to leave it on by default as it is today.

https://dlaa.me/blog/post/markdownlintanalyzeconfig
