### ISSUE TITLE
Improved "Quick Fix"

### ISSUE THREAD

**Issue by JensRoland** [DavidAnson/vscode-markdownlint#128]
Thanks for a wonderful extension! I would love to see more rules with quick fixes available, since those wavy lines all over my Markdown are driving me crazy.

Of course, many of the rules are non-trivial to quick fix, but some of the most common ones I encounter should be reasonably easy:

**hr-style**: If the extension has already identified the document's preferred hr style (it is showing it in the message after all) why not add the option to replace?

**first-line-heading**: Seems easy to quick fix

Finally, why not always offer the option under Quick Fix to "Disable this rule in project config"? That's a legitimate way to fix a violation if it's a rule you don't mean to follow, and a better user experience than a link to the JSON so I can add it myself (by the time I'm in the JSON, I have forgotten the code/ID of the rule anyway).

Anyway, thanks again for the great work!

**Comment by DavidAnson** [comment]
As you suggest, fixing some issues is not as clear as it might initially seem. Here are some thoughts about the issues you raise:

hr-style: This rule works by assuming the first style it encounters in a document is the preferred style for that document. But two different documents within the same project may have different styles, so it's not clear which style the overall project intended to use. Automatic fix (via the CLI) does not have an "undo" option, so the risk of changing an entire project to the wrong style is reasonably high and something I would want to avoid. (This is admittedly more of an issue for the CLI, but the fix implementation is common across all tools.) 

first-line-heading: This rule requires that the first line of a document be a top level heading. It would be easy to turn the first line of any document into a heading, but there is nothing to say that line makes sense as a heading or was ever intended to be one. In many cases, the document is missing a heading entirely and the first line is a sentence or paragraph of introduction. It would be wrong to turn that into a heading and would change the meaning of that document. Simply adding a heading called "Heading" would fix the violation, but that may be worse because now nothing is prompting the user to make further changes.

Disable this rule in project config: this is the least controversial, but still has some ambiguity. For example, what if the project does not have and configuration file? Should it create `.markdownlint.json`? Or the YAML version of that file? Either would be nice because it would automatically be respected by the CLI tools. However, it could introduce an entirely new file in the project and the user might be confused about why they need to add it to source control. Alternatively, they change could be made to the VS Code-specific settings, but the same source control concerns exist and now there is the problem that file-based configuration overrides setting-based configuration, so it's possible to change the "wrong" location and have no effect or override other settings.

Of these suggestions, the last has been on my list for a while, but I need to come up with an approach I feel good about first.

**Comment by DavidAnson** [comment]
Closing this per the comments above. The third item is still on my TODO list. If you want a dedicated issue, go ahead and open something specific, please.
