### ISSUE TITLE
Compatible with Code Server

### ISSUE THREAD

**Issue by cuso4-5h2o** [DavidAnson/vscode-markdownlint#149]
Hello,

I tried to install this extension on [Code Server](https://github.com/cdr/code-server) which is an online version of VS Code, but this extension doesn't work. There is a fatal error in the console that said `bundle.js` of this extension is missing. I searched for this problem, but no one mentioned it. And I tried to install this extension on a fresh Code Server environment on Ubuntu 20.04, this problem still happening. I solved this problem by manually compiling this extension from its codes, and moving the compiled `bundle.js` to the path of the extension.

```bash
$ sudo npm install webpack-cli
$ git clone https://github.com/DavidAnson/vscode-markdownlint
$ cd vscode-markdownlint
$ npm install
$ npm run compile
$ mv bundle.js ~/.local/share/code-server/extensions/davidanson.vscode-markdownlint-0.38.0/
```

Is this an issue with Code Server or this extension?

**Comment by DavidAnson** [comment]
This extension works correctly with VS Code which demonstrates that `bundle.js` is included in the package. (You can confirm this by downloading it from the extension page in the Marketplace.) It sounds like Code Server either isn't extracting the package correctly or isn't able to find the file once done, so the issue seems to be with that product, not this extension. If you find otherwise or there is some simple tweak to get this working, I will entertain it - but I would expect Code Server to support VS Code extensions as is.
