### ISSUE TITLE
0.40.2 no longer lints at all

### ISSUE THREAD

**Issue by thedewi** [DavidAnson/vscode-markdownlint#157]
On two of my machines*, 0.40.2 no longer lints at all.

I don't see any error messages and there's nothing that looks significant in the Output logs.

Downgrading 0.40.1 makes it work again.

* Windows 10 machines with VSCode 1.55.1 (user setup)

**Comment by DavidAnson** [comment]
Sorry! I've published 0.40.3 just now which reverts to the previous behavior based on two issues being reported this evening (the other of which is not a bug, it turns out). I'd previously tested these changes on multiple platforms, but will have a look at Windows again tomorrow. If you know of anything unusual about your configuration, please let me know!

**Comment by DavidAnson** [comment]
I had a quick look just now. This seems to be a Windows-specific issue related to the unconventional way VS Code represents paths on that platform (ex: `/c:/workspace/path`). I'll need to do some experimentation to figure out how to work around this in a platform-neutral way.

**Comment by thedewi** [comment]
Ah I see. Thank you very much for the rapid fix!

Windows sure has a lot of competing posix path schemes now (cygwin, mingw/msys, wsl, wsl, vscode)...

**Comment by DavidAnson** [comment]
To be honest, this was more my fault than theirs. I tested on Mac and Linux last time, but this time I will test on Mac, Linux, **and** Windows.!
