### ISSUE TITLE
Need addition rules for Pandoc markdown.

### ISSUE THREAD

**Issue by MagicPro1994** [DavidAnson/vscode-markdownlint#16]
I'm quite new to markdown. I couldn't remember all markdown syntax.
Your extension helps me a lot. But I found that your extension didn't full-support Pandoc Markdown.

Would you mind to take time to expand the rules?

**Comment by DavidAnson** [comment]
I wasn’t familiar with Pandoc, so I did a bit of reading, especially about its handling of Markdown:
http://pandoc.org/MANUAL.html#pandocs-markdown

As I understand, Pandoc supports a superset of the basic Markdown syntax. From the beginning, I wrote `markdownlint` to adhere to the Common Mark specification because of its popularity and clearly-defined rules for parsing:
http://commonmark.org/

I’m not ready to change that principle right now, but am happy to consider supporting Pandoc incompatibilities that are not invalid according to Common Mark.

If you can please identify some of the issues you’ve run into, I can look at what it would take to improve the experience.

Thanks for your help!

**Comment by MagicPro1994** [comment]
Thank you so much.

At this moment, I need to check if header identifiers. But I don't know how to add a rule to your extension.
For example: `#Header  {#identifier .class key=value}` is correct.
`#Header  {#identifier hello .class key=value}` is error

Error needs a red line under hello or display suggestions to follow a rule.
Please extend the rules if you have time.

**Comment by DavidAnson** [comment]
Migrated to `markdownlint` repo as https://github.com/DavidAnson/markdownlint/issues/76; closing this issue.
