### ISSUE TITLE
any error forces the output console open

### ISSUE THREAD

**Issue by af4jm** [DavidAnson/vscode-markdownlint#166]
Noticed this as a side effect of issue 165... every time I open a .md file the output console flies open with an error, and if I close it, it immediately reopens, forcing me to disable the extension... which instead of just turning itself off, it forces me to reload the window (yes, I know that's a separate bug, but 2 reports is enough for today)

**Comment by DavidAnson** [comment]
Errors switch to or show the output window because they are errors and something is not working and the user should know. (It worked in this case; you reported #165.) Errors should "never" happen, so this should not usually be something users have to deal with. VS Code lets you size the output window as you like, so this should not generally be an inconvenience. The fact that a restart is needed to disable an extension is VS Code behavior. I will look into the cause of the error, but don't think things should change for this issue.
