### ISSUE TITLE
Default of rule `"line-length": false` is `true` after creating a ".markdownlint.json"

### ISSUE THREAD

**Issue by redactedscribe** [DavidAnson/vscode-markdownlint#187]
"The default rule configuration disables MD013/line-length because many files include lines longer than the conventional 80 character limit:": https://github.com/DavidAnson/vscode-markdownlint#markdownlintconfig

I find it confusing that when creating a ".markdownlint.json" file, the supposed default above isn't in effect any more; When I create the json file, lines longer than 80 characters immediately get underlined with a squiggle in VS Code (with the json only containing `{ "no-hard-tabs": false }` for example).

Maybe it'd make more sense for the default of `"line-length": false` to be the case in both scenarios (with or without the json present)? People can then add `"line-length": true` to their ".markdownlint.json" if they want something other than the expected default behaviour.

There could be a good reason it is the way that it is, but it'd be less confusing to not have sentences suddenly be underlined for no apparent reason (that is, until you figure out what's going on and force the rule to its default again).

Thanks.

markdownlint v0.43.0

**Comment by DavidAnson** [comment]
The default behavior of ignoring long lines in the editor is in place because I expect people with this extension installed to open a variety of files that aren't already under some linting policy. About half of people disable the long line rule in configuration, so it would be noisy if it were on by default in the editor and applied to everything they opened.

However, anyone creating a configuration file for the linter is explicitly opting into linting and can (is expecting to) make their own choice about which rules to customize. The default behavior for the library and CLI has always been to enable everything by default so people see what the options are and can disable things they don't care about.

As you point out, this creates a slight inconsistency when moving from editor-based configuration to file-based configuration. However, I like the current behavior on both sides, so this is a natural consequence. For what it's worth, when you create a new configuration file in the editor with the markdownlint.openConfigFile Command, it will include the editor defaults for you.

**Comment by redactedscribe** [comment]
That makes sense, thanks for the explanation.

> For what it's worth, when you create a new configuration file in the editor with the markdownlint.openConfigFile Command, it will include the editor defaults for you.

I missed this in the README.md (maybe because the command to create a ".markdownlint.json" isn't beside the file's first mention -- which I admit I hastily created). There's a lot to read, but I don't think there's mention of the command adding the defaults when the file is created (which would've likely convinced me to use it over manually creating the file, thus avoiding the issue).

Anyway, thank you again.

**Comment by DavidAnson** [comment]
I'll use this issue as a reminder to mention the defaults in the README.
