### ISSUE TITLE
ERROR: Exception while linting with markdownlint-cli2: SyntaxError: Unexpected token # in JSON at position 0

### ISSUE THREAD

**Issue by ntsjv** [DavidAnson/vscode-markdownlint#194]
The terminal output shows the following errors a lot. I don't recall seeing these before, so I'm assuming they are a result of either VScode's update to latest stable version (1.60.2), or the plugin's update to 0.44.2.

[13.18.40] ERROR: Exception while linting with markdownlint-cli2:
SyntaxError: Unexpected token # in JSON at position 0
	at JSON.parse (<anonymous>)
	at y (c:\Users\username\.vscode\extensions\davidanson.vscode-markdownlint-0.44.2\bundle.js:37:626)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
	at async c:\Users\username\.vscode\extensions\davidanson.vscode-markdownlint-0.44.2\bundle.js:37:3718
	at async T (c:\Users\username\.vscode\extensions\davidanson.vscode-markdownlint-0.44.2\bundle.js:37:3660)
	
[13.42.09] ERROR: Exception while linting with markdownlint-cli2:
Error: Unable to parse 'c:/Users/username/folder1/folder2/.markdownlint.jsonc'; Unexpected number in JSON at position 1; Source contains multiple documents; please use YAML.parseAllDocuments()
	at c:\Users\username\.vscode\extensions\davidanson.vscode-markdownlint-0.44.2\bundle.js:33:27234
	at c:\Users\username\.vscode\extensions\davidanson.vscode-markdownlint-0.44.2\bundle.js:1:1560
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5

**Comment by ntsjv** [comment]
Turns out these errors pop up if you switch to VSCode's source control view to see your changes. A bug or a feature? :)

**Comment by DavidAnson** [comment]
Can you please share a repository and steps to reproduce the issue? If not, possibly just seeing the content of `c:/Users/username/folder1/folder2/.markdownlint.jsonc` would be enough. I don't think the parsing issue is new, BUT the new version respects hierarchical configuration in more scenarios and that may be why it's using this file when it did not used to.

**Comment by DavidAnson** [comment]
I can reproduce this - thanks for pointing out the need to view a diff of a Markdown file in the Source Control tab.

**Comment by DavidAnson** [comment]
This should be fixed in 0.44.3, thanks for the report! VS Code's "git" schema is now ignored - this means there will be linting issues in diffs against the working copy (which VS Code propagates from the file itself), but not against the index. I'm not sure either of these *should* show diffs, but I'm not looking to bypass VS Code's behavior for the working copy.

**Comment by ntsjv** [comment]
That was fast. :) Thank you!

**Comment by DavidAnson** [comment]
I started looking at this and realized it's behaving reasonably already. The error message above is actually 3 parts separated by `;`:
- `Unable to parse 'c:/Dev/ObjectStore/docs/.markdownlint.yml'`
  - This is a description added by `markdownlint` identifying the activity and the file
- `Unexpected token # in JSON at position 0`
  - This is added by the first parser that was attempted, it happens to be a JSON parser and the message quality is good
- `Expected a , in flow sequence`
  - This is added by the second parser that was attempted, it happens to be a YAML parser and the message is correct (the example is missing `,`), but it does not identify the line or character index

Parsers are customizable, in this case the YAML parser is https://github.com/nodeca/js-yaml which is fairly popular and by someone I trust. If its error improves, this scenario will improve automatically. I don't think it's worth adding more code to try to guess which parser should have been able to parse the input and favor that error message.

**Comment by svew** [comment]
I'm a bit confused by what you're saying, the issue is that currently there's nothing indicating that the two error messages are from different parsers, it reads like the JSON parser is throwing the `Expected a , in flow sequence` error. It doesn't seem like an issue that would resolve itself through updates to js-yaml, since the only ways I could see that benefiting is either js-yaml starts self-identifying itself as a yaml parser (something line `Expected a , in YAML flow sequence`) or it gives line numbers, which could still be misread as the JSON parser complaining on that line instead of YAML parser.

Maybe it would make sense to have that first line you mentioned printed twice, once for each parser:

```
Unable to parse config as JSON: 'c:/Dev/ObjectStore/docs/.markdownlint.yml'
Unexpected token # in JSON at position 0
Unable to parse config as YAML: 'c:/Dev/ObjectStore/docs/.markdownlint.yml'
Expected a , in flow sequence
```

Which would show:
1. That there are two parsers running on the file
2. Which error is coming from which parser, so you can handle them accordingly

**Comment by DavidAnson** [comment]
Agreed. I would like if js-yaml self-identified as a YAML parser because that would make this more clear. Your suggestion is also good and clear, however the code that outputs that message does not know what format each parser is trying to handle. Here's what that parameter looks like in code: https://github.com/DavidAnson/markdownlint#parsers. The code just calls each parser in the list and as soon as one successfully returns a result, it uses that. If none of them return a result, then it summarizes the exception messages from each of them as you see today. I could introduce a way to augment that parser list with hints about what each parser is trying to do, but that starts to feel like a lot of work for something that should be relatively rare.

**Comment by svew** [comment]
Ahh I see, I didn't realize the parser list was customizable instead of being hard-coded, that does make it a bit trickier... You're definitely right about this sort of mix-up being too rare to add hints for each parser, that would be a pain without much gain. 

Even without knowing which parser is looking for what, there may still be value in being clear that the two errors are coming from two different parsers, even if we don't know what format each is trying to parse:

```
[3:15:48 PM] ERROR: Exception while linting with markdownlint-cli2:
Error: Multiple parsers unable to parse 'c:/Dev/ObjectStore/docs/.markdownlint.yml'; PARSER 1: Unexpected token # in JSON at position 0; PARSER 2: Expected a , in flow sequence
	at c:\Users\wasvendd\.vscode\extensions\davidanson.vscode-markdownlint-0.44.4\bundle.js:33:27234
	at c:\Users\wasvendd\.vscode\extensions\davidanson.vscode-markdownlint-0.44.4\bundle.js:1:1673
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

It may be useful to incite the dev to investigate markdownlint parsers instead of throwing their hands up and wondering why it appears markdownlint is trying to only parse JSON, but frankly the easiest and clearest option at this point is to assume a dev with my same frustrations will stumble on this thread like I did and find your answer fixed our dumb problem :)

**Comment by DavidAnson** [comment]
Ha! I like your idea about updating the list to be more clear about multiple parsers. I'll do that for the next release. Thanks!

**Comment by DavidAnson** [comment]
Here's that change: https://github.com/DavidAnson/markdownlint/commit/7330ea49463490115337c4365f9c6c4a215277d1

**Comment by svew** [comment]
Looks good, thanks for the update!
