### ISSUE TITLE
No errors reported.  Unsure if extension is even working.

### ISSUE THREAD

**Issue by bumper314** [DavidAnson/vscode-markdownlint#220]
I'm using [VSCodium](https://vscodium.com/) 1.63.2 on macOS 10.14.6.  I've installed and enabled markdownlint 0.45.0 and even restarted VSCodium.

Here's my settings.json
```
{
    "workbench.colorTheme": "Default Light+",
    "markdownlint.config": {
        "default": true,
        "MD001": true,
        "MD003": { "style": "setext" },
        "no-hard-tabs": false
    }
}
```

I've opened a large .md file with many issue sure to violate the linting rules I have defined, and yet I don't see any linting errors in the PROBLEMS tab.  I don't use VSCode much, so I'm at a complete loss as to what to check.  Any help is appreciated.

**Comment by DavidAnson** [comment]
If your path has parentheses in it, there is a known issue that it won't be analyzed. Otherwise, please check the "markdownlint" section of the output panel to see if there are any errors there. If you can point to the Markdown document, I will make sure it can be analyzed properly. You might also try official VS Code builds, though I'm not expecting that to be the issue.

**Comment by bumper314** [comment]
Indeed, a folder in my path had parenthesis.  I have moved the file and linting is now returning errors as expected (1001 infact… ooph).  Thank you very much for the help David.

**Comment by DavidAnson** [comment]
Cool. The next release should have a fix for the parentheses bug.
