### ISSUE TITLE
Ignore inline HTML tags when it has an attribute

### ISSUE THREAD

**Issue by Blyxyas** [DavidAnson/vscode-markdownlint#222]
Is very common center the main title with `<h1 align=center>`, I think the linter should ignore the tags with attributes. So the users doesn't have to customize a config file.

Thanks for the extension :)

**Comment by nschonni** [comment]
I'm not sure if it is very common, but I have seen it. HTML5 doesn't support the `align` attribute https://www.tutorialspoint.com/How-to-set-Heading-alignment-in-HTML

Allowing tags with attributes by default would also allow link tags like `<a href="mylink>foo</>` when the style should be `[foo](mylink)` that would otherwise be flagged.
I might make sense as an opt-in for MD033 though

**Comment by DavidAnson** [comment]
The point of MD033 is to call out that HTML is something of an anti-pattern in Markdown: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033

MD041 already allows the h1/align pattern you describe, but relies on the user opting into allowing HTML first: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md041

Allowing any HTML tag with attributes seems like it would lead to confusion around why some tags work sometimes but not always. The way it is now is clear: HTML tags are not allowed by default but can be permitted, including by name if desired.

FYI, this issue may be interesting to you: https://github.com/DavidAnson/markdownlint/issues/464

**Comment by DavidAnson** [comment]
Good point about a/href, @nschonni.

**Comment by Blyxyas** [comment]
Ok, thanks for answering
