### ISSUE TITLE
VSCode error "Unexpected token # in JSON"

### ISSUE THREAD

**Issue by borekb** [DavidAnson/vscode-markdownlint#230]
Hi, for a few days I've been getting this error in VSCode:

![Screen Shot 2022-02-18 at 11 46 36](https://user-images.githubusercontent.com/101152/154668264-99f988ea-d7af-4ca7-b7f3-4303439c6b84.png)

As text:

```
[9:56:22 AM] ERROR: Exception while linting with markdownlint-cli2:
Error: Unable to parse '/Users/borekb/dev/shoptet/sofa/docs/docs/.markdownlint.jsonc'; Parser 0: Unexpected token # in JSON at position 0; Parser 1: A collection cannot be both a mapping and a sequence
    at /Users/borekb/.vscode/extensions/davidanson.vscode-markdownlint-0.46.0/bundle.js:33:29570
    at /Users/borekb/.vscode/extensions/davidanson.vscode-markdownlint-0.46.0/bundle.js:1:2260
```

In the terminal, all works fine:

```console
$ yarn markdownlint-cli2 '**/*.md'
markdownlint-cli2 v0.1.3 (markdownlint v0.23.1)
Finding: **/*.md !**/node_modules/** !**/.next/** !**/dist/**
Linting: 80 file(s)
Summary: 0 error(s)
```

Also strange is that the VSCode error mentions a file `/Users/borekb/dev/shoptet/sofa/docs/docs/.markdownlint.jsonc` which doesn't exist on my disk and I'm not sure where it's coming from.

The only markdownlint config we have in the repo is repo-root-level `.markdownlint-cli2.js` with this content:

```js
require('./.pnp.cjs').setup();

const path = require('path');

module.exports = {
  config: {
    MD007: {
      indent: 4,
    },
    MD013: false,
    MD014: false,
    MD040: false,
    MD029: false,
    MD033: false,
    MD026: false,
    MD009: { br_spaces: 0 },
    MD031: { list_items: false },
    'graphql-examples': {
      schema: path.join(__dirname, 'packages/graphql/schema.graphql'),
      globs: [`${__dirname}/docs/docs/**/*.md{,x}`],
    },
  },
  ignores: ['**/node_modules/**', '**/.next/**', '**/dist/**'],
  customRules: ['@shoptet-private/markdownlint-graphql-examples'],
};
```

**Comment by DavidAnson** [comment]
I transferred it. Please have a look at the other issues like this (link below). I think this will end up being some other extension you have installed playing tricks with the way they represent file URLs. I've been excluding those as I learn about them.

https://github.com/DavidAnson/vscode-markdownlint/issues?q=is%3Aissue+%22unable+to+parse%22

**Comment by borekb** [comment]
Thanks for transferring the issue, I should have searched in this repo, sorry..

Could this extension possibly check whether the file exists on the disk or not, and if not, swallow the parse errors?

**Comment by DavidAnson** [comment]
It may already be doing that. :) Your case may turn out to be different, but when I've looked at this before, the problem occurs in a part of the code that is checking for existence of all the different configuration files and then trying to read the first that it finds. Some extensions abuse the URI format that VS Code uses and report that a file exists and contains data when it does not. Please experiment a little to see if you can tell which extension is causing this and I will try to confirm locally.

**Comment by borekb** [comment]
I was on a holiday for a week and it stopped happening 🤷‍♂️. Closing this for now, thanks for your help!

**Comment by borekb** [comment]
The issue is back and I have some new info so will be posting it here for future reference – hope you don't mind.

**Comment by borekb** [comment]
### Strange interaction with [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) extension

This is an error that I can now get reliably with the steps described below:

```
[5:47:53 PM] ERROR: Exception while linting with markdownlint-cli2:
Error: Unable to parse '/Users/borekb/dev/shoptet/sofa/docs/docs/.markdownlint.jsonc'; Parser 0: Unexpected token # in JSON at position 0; Parser 1: A collection cannot be both a mapping and a sequence
    at /Users/borekb/.vscode/extensions/davidanson.vscode-markdownlint-0.46.0/bundle.js:33:29570
    at /Users/borekb/.vscode/extensions/davidanson.vscode-markdownlint-0.46.0/bundle.js:1:2260
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[5:47:53 PM] ERROR: Exception while linting with markdownlint-cli2:
SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/borekb/.vscode/extensions/davidanson.vscode-markdownlint-0.46.0/bundle.js:37:4010
    at /Users/borekb/.vscode/extensions/davidanson.vscode-markdownlint-0.46.0/bundle.js:37:4879
    at async Promise.all (index 0)
    at /Users/borekb/.vscode/extensions/davidanson.vscode-markdownlint-0.46.0/bundle.js:37:8417
    at T (/Users/borekb/.vscode/extensions/davidanson.vscode-markdownlint-0.46.0/bundle.js:37:8359)
```

It happens when I open a **diff** in our `whats-new.md` file, and only if I open this diff via the _GitHub Pull Requests and Issues_ extension:

![Screen Shot 2022-03-22 at 17 54 25](https://user-images.githubusercontent.com/101152/159533580-79e0be01-5451-4d66-b4cb-b07ede020d3a.png)


I also have another extension that can open diffs and when I use that, there's no such issue:

![Screen Shot 2022-03-22 at 17 50 05](https://user-images.githubusercontent.com/101152/159533367-ee4d80ef-732f-4510-90bb-584308bc0275.png)

I noticed that the GitHub PR extension uses the `review:/...` paths, maybe it's related? I know very little about this at all.

**Comment by DavidAnson** [comment]
Thank you for the details! I'll have a look for the next release. What I found is that some extensions do weird/wrong things with how they represent pads to files and that can lead to content for the wrong file being returned. That shows up like what you see here where this extension thinks it is getting a JSON configuration but ends up with something else. I've been adding such extensions to a block list and expect to do the same here.

**Comment by alexr00** [comment]
Hi 👋 I'm a developer on VS Code and https://github.com/microsoft/vscode-pull-request-github, the other extension that is involved in this issue. Is the issue usually that you `stat` a file and it looks like it exists, even when it doesn't?

**Comment by DavidAnson** [comment]
@alexr00

Here are the list of problematic extensions I've identified so far: https://github.com/DavidAnson/vscode-markdownlint/blob/main/extension.js#L27-L39

The general pattern for errors like this exception/parse failure is that markdownlint builds a new path to a file based on the workspace folder Uri from VS Code and the other extension responds by providing the contents of a different file. Per my notes in the code, two of the extensions do this because they store the file path in Uri.query instead of the path section of the Uri where it belongs.

My code that does the mapping has to jump through a few hoops for special cases and can be found here: https://github.com/DavidAnson/vscode-markdownlint/blob/main/extension.js#L123-L147

Based on issue #179, it looks like I previously referenced GitHub.vscode-pull-request-github in order to prevent linting of the comment field as a Markdown document (inappropriate, but not an exception). However, it seems a similar issue may have been introduced in that extension that leads to the exception. Perhaps you can tell easily?

**Comment by DavidAnson** [comment]
@alexr00 I had a quick look at the code for the vscode-pull-request-github extension and it seems to do the same problematic thing - `filePath` is stored in the Uri's `query` instead of `path`: https://github.com/microsoft/vscode-pull-request-github/blob/main/src/common/uri.ts#L89-L118

I can see why this representation may be convenient for an extension, but if there is no standard for how paths are stored in a Uri, this seems to discourage interoperability with other extensions. Of course, I may be using Uri wrong - if there's a good way to transform a workspace Uri into a reference to an arbitrary file, I would be happy to update my code!

**Comment by alexr00** [comment]
Thanks for the details and pointers!

In vscode-pull-request-github the uri that has a `filePath` in the `query` also has a value in `path` which corresponds to the the `path` that vscode-pull-request-github uses for referencing files that come from github, so we can't change that. Those uris point to files that may not exist on disk at all. We use the `query` to give a quick and easy pointer back to the file on disk (if it exists there) for internal use in the extension.

I think the problem is probably that vscode-pull-request-github basically says _all_ files with scheme `review` exist, even though they clearly do not. So, when you go looking for the lint file you end up looking for a file with scheme `review` and it looks like it exists. Then, when you actually get the file it's an empty file (we end up returning `new TextEncoder().encode('')` and this is probably what causes the json error).

I see three possible fixes:
1. I can stop saying that all `review` files exist in vscode-pull-request-github. I'm not sure that this will be feasible, but I'll take a look as this is most correct fix.
2. vscode-markdownlint could check if the lint files it finds are empty.
3. vscode-markdownlint could convert all uris with unexpected `scheme` to whatever the `scheme` of the workspace is (could be done with `vscode.workspaceFolders` and seeing what the scheme of those are). I would caution against this unless you're confident that it's the right fix since it may cause interop problems with other extensions.

**Comment by DavidAnson** [comment]
@alexr00 Thank you for the help and engagement!

One thing I should call out is that I don't think it's necessary to lint files under review, so my existing mechanism of excluding by scheme is probably fine in the short term. (It would be neat if this worked, but the primary scenario is editing.)

Thinking about your suggestions, it's probably helpful to describe what the extension is doing. As part of linting, it supports multiple different named configuration files and sniffs for the first one it finds in priority order. Once it believes a file exists, it commits to that file and reads and parses the content.

So I like your first suggestion because the extension will stop believing files exist that don't. However, because the extension is always passing paths in Uri.path vs. Uri.query, it will probably never find configuration files even when they do exist and that will lead to incorrect results. This isn't ideal, but it is the situation that already exists when running in the browser – though I have plans to fix that.

Checking for empty files is an interesting idea and I may be able to do something with that, but it's already too late when a file is being read because that file has been chosen for use instead of any others. Additionally, while an empty file is not valid JSON, I think it could be valid YAML and so it could be a valid scenario in practice.

Your scheme manipulation suggestion is interesting and I need to think more about it. You have scared me by suggesting it could create interoperability problems and I worry about trying to infer too much about how another extension represents paths. I'm trying to do the simplest possible thing already and it still hasn't kept me out of trouble. :)

**Comment by alexr00** [comment]
>  As part of linting, it supports multiple different named configuration files and sniffs for the first one it finds in priority order.

This priority order is very interesting to me. Could your priority order also include a scheme? Example:
1. Scheme of first folder in `vscode.workspaceFolders` is used first
2. Use that scheme to search for all the files you sniff for.
3. Then, repeat step 2 with each new scheme for each of the folder in `vscode.workspaceFolders`.
4. If no file is found, then fall back the scheme of the current file. and repeat step 2.

**Comment by DavidAnson** [comment]
Ooh, maaaybeee. The complete realization of what you suggest would be a little tricky because there are actually two entities at play here. The CLI knows how/what to lint and allows callers to provide a custom "fs" implementation and the extension calls into it with an implementation that wraps the VS Code file system wrappers (I linked to this earlier). To do what you suggest fully may need to cross the abstraction boundary. However, I could probably override the scheme with that of the main workspace unconditionally and let the code run as today, BUT that seems to mean combining the representation of a file from one scheme and configuration from another. Taking a step back, I potentially only want to lint in scenarios where the file content is represented by some kind of a file system that can be probed for configuration. Thus far, I've been excluding schemes that turned out to be troublesome. A better approach might be to include only schemes that are known to be file system-like. However, beyond "file", I didn't see that list exposed by VS Code anywhere and I know of at least a couple schemes it uses for virtual, etc. scenarios.

**Comment by alexr00** [comment]
> However, beyond "file", I didn't see that list exposed by VS Code anywhere

This is why I suggested using `vscode.workspaceFolders` since in vscode.dev the files actually don't have a `file` scheme. 

I'm still planning on investigating a fix from the vscode-pull-request-github-side too, I'll try to take a look this week.

**Comment by DavidAnson** [comment]
Ok, I wasn't thinking about that as a proxy for "file system". I like the idea, thanks! My fear would be if each workspace in the list used a different scheme (not sure that's possible?), but I already give preference to the first, so could do that here as well. I will try this out!

**Comment by DavidAnson** [comment]
(I may still need an allow list for schemes for cases when a workspace is not open.)

**Comment by DavidAnson** [comment]
I made the simpler/safer change first: https://github.com/DavidAnson/vscode-markdownlint/commit/de896687a01d9d3be24e23ab524a927e2404f8ad

**Comment by DavidAnson** [comment]
I published a new version of the extension last night that I hope addresses this. Please let me know if you still see a problem.

**Comment by borekb** [comment]
I've tested the [problematic scenario](https://github.com/DavidAnson/vscode-markdownlint/issues/230#issuecomment-1075390838) and all's OK – that's great! 🎉 Thanks a lot.
