### ISSUE TITLE
Custom rule giving: This rule threw an exception: Cannot read properties of null (reading 'forEach')

### ISSUE THREAD

**Issue by andrewnicols** [DavidAnson/vscode-markdownlint#239]
I've written a custom extension to replace apostrophe (`’`) with a single-quot (`'`).

This extension works without issue with markdownlint-cli and markdownlint-cli2 on the CLI, but shows the following error when used with vscode:

```
MDLDOC001/no-apostrophes: Use single-quote instead of apostrophe [This rule threw an exception: Cannot read properties of null (reading 'forEach')]
```

The configuration for markdownlint-cli2 looks like the following:
```
// .markdownlint-cli2.yaml
customRules:
  - ./.markdownlint/MDLDOC001

# Define glob expressions to use (only valid at root)
globs:
  - '{docs,general}/**/*.{md,mdx}'
  - '{docs,general}/*.{md,mdx}'
  - '*.{md,mdx}'
```

And even pairing my rule down to the bare minimum, with no actual checks, I get this error:
```js
//  .markdownlint/MDLDOC001.js.
module.exports = {
    names: ['MDLDOC001', 'no-apostrophes'],
    description: 'Use single-quote instead of apostrophe',
    tags: ['punctuation'],
    function: function MDLDOC001(params, onError) {
    }
};
```

This error appears on the first line of the markdown on any markdown file, for example:

```
// example.md
---
title: Example
---

The error shows for me on this line
```

Given I am unable to reproduce this with either `markdownlint-cli` or `markdownlint-cli2` through the console, but I can do so via the vscode extension, I'm reporting this issue here.

I'd love to help debug this, but I've not done any vscode extension development, and haven't found a way of actually debugging this so far.

**Comment by andrewnicols** [comment]
Here's a simple example repo: https://github.com/andrewnicols/markdownlint

CLI output:
```
➜  markdownlint git:(main) yarn markdownlint-cli2
yarn run v1.22.18
warning package.json: No license field
$ /Users/nicols/git/tmp/markdownlint/node_modules/.bin/markdownlint-cli2
markdownlint-cli2 v0.4.0 (markdownlint v0.25.1)
Finding: *.md !/_*/* !/_*
Linting: 1 file(s)
Summary: 1 error(s)
example.md:5:4 no-apostrophes Use single-quote instead of apostrophe [Expected: Foo'bar; Actual: Foo’bar] [Context: "Foo’bar"]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

And the same in vscode:
<img width="2040" alt="Screen Shot 2022-05-04 at 14 42 35" src="https://user-images.githubusercontent.com/370047/166633611-4bf33371-0d04-4156-bd03-cbd9639d9ccf.png">

**Comment by DavidAnson** [comment]
Just reading this on my phone, I think the issue is that your rule package does not declare any dependencies. When you install it along with the CLIs, those implicitly bring in the core library and the helpers package, so your two require statements succeed. However, when running under VS Code, there is no shared node_modules directories and so I expect that both require statements will fail. To fix this, you should be able to explicitly depend on the markdownlint-rule-helpers package which exists for the purpose of reuse like this. It exports a function you can use to generate lineMetadata, so you can get everything you need from that and not reference the core markdownlint library package at all.

PS: Based on the actual error, I think the first require may be succeeding, possibly because of the way Node caches modules but I think the second is failing and so it calls into forEachLine with a null first parameter and then crashes trying to iterate that.

**Comment by andrewnicols** [comment]
Thanks for the suggestion - that combination of things, witih an additional restart of vscode solves the issue.

Without the vscode restart the error persisted.

I wonder if this can be made clearer somehow for future sufferers of this.

Thanks.

**Comment by DavidAnson** [comment]
VS Code (via Node) caches module loads which is probably why the restart was needed. Glad you got this working!
