### ISSUE TITLE
Linter picking up emphasized all-caps as a header

### ISSUE THREAD

**Issue by PrincessColumbia** [DavidAnson/vscode-markdownlint#276]
I have a file I'm converting to markdown where the following appears:

`*KNOCK-KNOCK*`

This is an appropriate bit of text and is not a header, but the linter keeps spitting out the following error:

`MD036/no-emphasis-as-heading/no-emphasis-as-header: Emphasis used instead of a headingmarkdownlint[MD036](https://github.com/DavidAnson/markdownlint/blob/v0.27.0/doc/md036.md)`

**Comment by DavidAnson** [comment]
Your example looks like the kind of thing that rule warns about, so it is warning you legitimately: https://github.com/DavidAnson/markdownlint/blob/main/doc/md036.md

Because that structure is deliberate, you probably want to disable the rule for that line, or perhaps the file or maybe even your entire project: https://github.com/DavidAnson/vscode-markdownlint#configure
