### ISSUE TITLE
.markdownlintignore file is not honored in multiroot workspace

### ISSUE THREAD

**Issue by mig8447** [DavidAnson/vscode-markdownlint#285]
I have a multiroot workspace. Added a .markdownlintignore file at the root of the workspace with some rules and they were not honored. After, I added the rules to the vscode setting markdownlint.ignore and they were honored

Extension version: v0.49.0

**Comment by DavidAnson** [comment]
This should work in the root of a normal project. Multi-root workspaces are newer and may not be handled. Glad you have a workaround.

**Comment by DavidAnson** [comment]
My interpretation of the VS Code documentation for multi-root workspaces (and workspaces in general) is that they exist as a concept to make VS Code configuration and project management easier. I don’t see anything to suggest that non-VS Code files should be placed in the multi-root folder and expected to apply automatically to all workspaces.

As you point out, applying ignore settings within the VS Code settings system automatically respects normal and multi-root workspaces, so that is what I recommend.

While I agree that what you propose is possible, I don’t think it’s what VS Code intends and I am not planning to add support unless it becomes part of the ecosystem.

https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by mig8447** [comment]
Even when the file is put in one of the folders of the multi-root workspace, the rules weren't honored so I think that's still a bug

**Comment by DavidAnson** [comment]
@mig8447 Can you point to a repository that demonstrates the issue? I'll have a look.

**Comment by DavidAnson** [comment]
Because the extension only listens to the workspace root path (basically the first folder) for changes to configuration/options/ignore files, changes to such files within other workspace folders will not be detected. That's currently deliberate but might need to change. Even with that, I'm seeing a couple of problems as I try to reproduce this locally. I should be able to improve things here.
