### ISSUE TITLE
Pasting is slow. 

### ISSUE THREAD

**Issue by JohnBentleyDpi** [DavidAnson/vscode-markdownlint#294]
Pasting any text into a markdown file causes a slowly spinning wait icon before the text is inserted into a file. Does not occur in non-markdown files. Does not occur when extension disabled.

I've disabled/reenabled all extensions to isolate the cause to this extension. Recently introduced behaviour (some weeks).

**Comment by DavidAnson** [comment]
To be clear, have you narrowed it down to **an** extension or **this** extension? I've gotten multiple reports of slow extensions that turned out to be due to a different extension. If you could please confirm this doesn't happen with all extensions disabled and does happen with only this extension enabled, that would be a good start. If so, please confirm you are using the latest version of this extension and see #291 for good next steps to collect a CPU trace. Obviously, pasting text into a Markdown file doesn't usually cause the problem you are reporting and if it happens when pasting "hello world" into an empty Markdown file, then it isn't a syntax parsing issue.

**Comment by DavidAnson** [comment]
I haven't heard about something like this from anyone else and people paste into Markdown documents many thousands of times a day, so my working assumption is that it has something to do with your configuration. Some other things to try your scenario on:

- Different Markdown documents
- Another computer
- Open https://vscode.dev/ and install the extension
- VS Code Insiders build
- Uninstall and reinstall the extension and/or VS Code

In particular, https://vscode.dev/ is interesting because it's easy and a completely different install.

**Comment by DavidAnson** [comment]
Closing for lack of action/data.
