### ISSUE TITLE
Feature: [MD049] Ignores style of TableOfContent

### ISSUE THREAD

**Issue by cloudy81** [DavidAnson/vscode-markdownlint#298]
When using Markdown files for azure devops we need to add table of content with following style
![image](https://github.com/DavidAnson/vscode-markdownlint/assets/43065907/c8204c5a-1cbc-4954-9551-3ef1c6e1300c)

But the check of MD049 shows than inconstancy  
![image](https://github.com/DavidAnson/vscode-markdownlint/assets/43065907/eb4c7e42-67bc-4816-9780-578baf0b14e2)

Is it possible to ignore table of content for check

**Comment by cloudy81** [comment]
I have seen the same question [here](https://github.com/DavidAnson/markdownlint/issues/734).

I tried also to suppress it
![image](https://github.com/DavidAnson/vscode-markdownlint/assets/43065907/54243bfc-5104-4d6e-893b-14029dcf5000)

Would be nice to have a solution for that

**Comment by DavidAnson** [comment]
This is a duplicate as you point out. Also, `<!-- markdownlint-disable-next-line -->` already exists: https://github.com/DavidAnson/markdownlint#configuration

**Comment by DavidAnson** [comment]
Actually, it's not a duplicate issue because the issue you link to above is about parsing _before_ the table of contents is inserted and yours seems to be about parsing _after_ it is inserted. From what I see of your example, the ability to disable rules for the next line will not be helpful here because you are examining code after the expansion and it contains multiple lines. In your case, the issues reported are correct that the emphasis style of asterisk is being used. If you have previously used the underscore style, then this is legitimately inconsistent. You could standardize on the asterisk form instead, change the TOC generator to produce underscores in the table of contents, or disable this rule for that part of the document or for your project.
