### ISSUE TITLE
Problems loading reference

### ISSUE THREAD

**Issue by unional** [DavidAnson/vscode-markdownlint#357]
Saw this when opening `.vscode/settings.json`:

```sh
Problems loading reference 'https://raw.githubusercontent.com/DavidAnson/markdownlint/v0.35.0/schema/markdownlint-config-schema.json': Unable to load schema from 'https://raw.githubusercontent.com/DavidAnson/markdownlint/v0.35.0/schema/markdownlint-config-schema.json': .
```

I can access the file:
![{945AE74E-C6AA-4627-9D34-44589B612E05}](https://github.com/user-attachments/assets/77b49ffe-1b59-4200-bc5a-c41cf90fa958)

Maybe the schema has some syntax issue?

**Comment by DavidAnson** [comment]
As you note, that file is accessible. You can review various tests that ensure the validity of that schema file here: https://github.com/DavidAnson/markdownlint/blob/fe02674ce0119b0ae2c260e326ef6f74693c35e0/test/markdownlint-test.js#L943

Because this seems to be working for everyone else and there have been no recent changes, I'm inclined to think this has something to do with your configuration or machine.

If you are able to try on another machine or with the Insiders build, it would be interesting to know if this reproduces there.

**Comment by unional** [comment]
Yeah, it seems like my environment issue. Somehow my wsl suddenly lost network connection...

thanks for the quick response. 🍻

**Comment by PriceHu** [comment]
Hello, sorry for posting in a closed issue, but does anyone know that if this will prevent the extension from runing normally?

I'm getting the excat same error when inspecting and changing settings in `settings.json` recently, with the error being:
```
getaddrinfo ENOENT raw.githubusercontent.com
```
For me this is common because we have difficulties accessing some github domains in our region. I can manage to bypass this using proxy or something, but I can't have it open all the time. For now the extension is working as expected when I do work with markdown files, so I'm curious if this remote file is a backup config or if it's mandatory. Thanks.

**Comment by DavidAnson** [comment]
The schema file is used by VS Code to provide IntelliSense for the corresponding JSON. It is not used by the markdownlint extension and its absence should not be a problem for VS Code. (If it is, that's a bug they should fix.)

**Comment by unional** [comment]
One possible way to resolve this is bundling the schema within the extension and ask vscode to use that schema instead. Company network may block the domain.
