### ISSUE TITLE
Cannot open link on *nix due to missing execute bit on xdg-open script used by dependency opn

### ISSUE THREAD

**Issue by jdumas** [DavidAnson/vscode-markdownlint#4]
Hi,

Archlinux user here. When I click on the tooltip icon of a linted error/warning, it fails to open it with the following message:

    Running the contributed command:'vscode-markdownlint.openLink' failed.

Could it be that this package is missing a dependency or something?

**Comment by DavidAnson** [comment]
Wow, thanks for reporting this!

In order to open web links in a cross-platform way, `vscode-markdownlint` uses the [opn package](https://www.npmjs.com/package/opn) which uses the `xdg-open` script which it bundles alongside. However, when VS Code installs the extension and its dependencies, the *nix `execute` bit is **not** set on `/home/ubuntu/.vscode/extensions/DavidAnson.vscode-markdownlint-0.6.0/node_modules/opn/xdg-open
` (or the corresponding path for your user name and version).

> If you set the `execute` bit on this file yourself, it should fix the problem you're seeing. I've confirmed that it does in a vanilla Ubuntu Live CD environment.

What *should* be happening here is that VS Code preserves the execute bit, but what I suspect is happening is that it's not because I package on Windows/NTFS and there is no such bit set on that file - or maybe VS Code wouldn't have preserved it even if I published from *nix.

1. I will open a bug against VS Code - but am not sure there's a good solution for publishing Windows->*nix per above.
2. I will investigate whether publishing from *nix does the right thing or whether I could tweak the extension package before uploading it from Windows.
3. I will look into whether `opn` could be replaced by another library that doesn't have this problem.

Thanks again!

**Comment by jdumas** [comment]
Thanks for looking into this.

I can confirm that if I `chmod +x` the file you pointed out, it does work fine.
Given that `xdg-open` is just a shell script, you can probably call it directly via `sh` (e.g. `sh .../xdg-open`) (but maybe this implies patching `opn`, which you don't want).

**Comment by DavidAnson** [comment]
Please upgrade to `vscode-markdownlint` version `0.6.1`. I published that release from Linux just now and it seems to have preserved the `execute` bit for `xdg-open` which fixes the problem you were having.

I'll open a bug against VS Code and another against `opn` (based on your suggestion above) and link both to this issue.

Thank you!
