### ISSUE TITLE
Relaxed rules in code blocks

### ISSUE THREAD

**Issue by okonomiyaki3000** [DavidAnson/vscode-markdownlint#42]
Markdown linting rules shouldn't apply inside of a code block. The linter should probably just ignore anything enclosed by delimiters of three backticks.

**Comment by DavidAnson** [comment]
Which rules? Can you give examples, please?

**Comment by okonomiyaki3000** [comment]
The only one I've encountered was "no-hard-tabs" but I assume there could be others that might come up considering what goes inside of code blocks is not Markdown and may follow a different style.

**Comment by DavidAnson** [comment]
MD010 already supports ignoring tabs in code blocks via the `code_blocks` parameter: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md010---hard-tabs

Any others?

**Comment by okonomiyaki3000** [comment]
Ah, I see! No issue then.

**Comment by DavidAnson** [comment]
Great! If you find something else, do please let me know.

**Comment by HankB** [comment]
The Linter also complains about trailing spaces in fenced code blocks. (MD009)

Thanks!

**Comment by DavidAnson** [comment]
Trailing spaces in code blocks are reported because they are almost never significant and people are likely to want to fix them for the same reason they want to do so outside a code block.

The parameter mentioned above applies only to that rule, not globally. To set it in the VS Code settings JSON would look something like this: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#markdownlintconfig

Note that rules are nested and parameters apply beneath them. The auto-complete editing experience for that file should help you get this right now that you know what the basic structure will look like.

**Comment by HankB** [comment]
Thanks for the help setting this (and the quick reply.)

I'm copying hundreds of lines of console output to text files and formatting a relatively few comments using Markdown. As such I'm not very likely to want to fix the offending text. I guess that would force me to learn regexes in code (or figure out how to use the 'vi' mode.)

Thanks!

**Comment by DavidAnson** [comment]
If a rule is too noisy, you can always disable it. Please let me know if you are still stuck!
