### ISSUE TITLE
[Feature] autofix all document

### ISSUE THREAD

**Issue by ctf0** [DavidAnson/vscode-markdownlint#85]
is it possible to have a way to autofix the whole document issues instead of one by one ?

**Comment by DavidAnson** [comment]
Not today, but it is on the list. I first want to change how fixes are identified by the core library, then surface that here in the extension, and then it should be fairly straightforward to offer a command to fix everything at once.

**Comment by ctf0** [comment]
many many thanx for the new command, just a small headsup, not all errors are fixed ex.`[markdownlint] MD004/ul-style: Unordered list style [Expected: dash; Actual: plus]`

**Comment by DavidAnson** [comment]
That’s right. Only the list of “fixable“ commands at the end of the section are fixed: https://github.com/DavidAnson/vscode-markdownlint/blob/master/README.md#rules

Rules like MD004 could be fixed automatically in cases where the user has chosen a specific style, but not when they use the default “consistent“ style. So, for now, those rules are not automatically fixed in any case.

**Comment by ctf0** [comment]
oh okay, many thanx for ur help
