### ISSUE TITLE
MD007: Detect _Unordered list indentation_ based on Tab Size?

### ISSUE THREAD

**Issue by kenorb** [DavidAnson/vscode-markdownlint#86]
When I've Tab Size of 4 (which I think it's default), when generating TOC via [markdown-toc](https://github.com/AlanWalk/markdown-toc), the markdownlint complains about:

> [MD007 - Unordered list indentation](https://github.com/DavidAnson/markdownlint/blob/v0.15.0/doc/Rules.md#md007)

I've checked, and in settings I had _Editor: Tab Size_ set to 4. When changed to 2, TOC has been regenerated to use 2 spaces. So I think TOC extension works as expected (it changes on settings), however _markdownlint_ doesn't respect the value of _Tab Size_.

I think it should read what's set for _Editor: Tab Size_ and rely on that.

Related: AlanWalk/markdown-toc/issues/60

**Comment by DavidAnson** [comment]
Pressing the `Tab` key in VS Code can be configured to insert a tab character or some number of spaces (4 by default). https://code.visualstudio.com/docs/editor/codebasics#_indentation

In a Markdown file, the CommonMark specification says that tab characters always correspond to 4 (space) characters. https://spec.commonmark.org/0.29/#tabs

Therefore, the only sensible configuration for editing Markdown in VS Code is to have `editor.tabSize` set to the default value of 4 spaces. Any other value means that files with tabs vs. those with spaces will have different structure and rendering after the same edits have been applied by the user.

The fact that other Markdown extensions change their behavior based on `editor.tabSize` seems problematic. For example, generating a table of contents by building an unordered list with `editor.tabSize` set to 1 would result in incorrectly nested structure because one space is not enough to start a sublist. Similarly, an `editor.tabSize` setting of 6 or more would cause problems because that is too many to start a sublist. [(Examples of both.)](https://dlaa.me/markdownlint/#%25m%23%20Issue%2086%0A%0AOne%20space%0A%0A-%20Table%20of%0A%20-%20contents%0A%20-%20with%20one%0A%20%20-%20space%0A%0ASix%20spaces%0A%0A-%20Table%20of%0A%20%20%20%20%20%20-%20contents%0A%20%20%20%20%20%20-%20with%20six%0A%20%20%20%20%20%20%20%20%20%20%20%20-%20spaces%0A)

The only way to reliably generate content is for extensions to ignore `editor.tabSize` and use a constant number of spaces.

For unordered lists, both 2 and 4 spaces are valid. Neither is unambiguously correct, so either might reasonably be used within a file. https://spec.commonmark.org/0.29/#motivation

Which is why this project's `MD007/ul-indent` rule can be configured to support either approach (though it defaults to 2). https://github.com/DavidAnson/markdownlint/blob/v0.15.0/doc/Rules.md#md007

It is reasonable to ask that VS Code Markdown extensions come up with a way to agree on this value, and I would be open to doing so. However, I believe I have shown here that `editor.tabSize` is not the right choice.
