### ISSUE TITLE
Allow metadata before first header by default? (MD041)

### ISSUE THREAD

**Issue by unional** [DavidAnson/vscode-markdownlint#9]
```markdown
---
some-yml-metadata: something
---

# First header
```

I can create a config file to ignore MD041 for this, but is this common or conventional enough to make it an exception to the rule MD041?

**Comment by DavidAnson** [comment]
That warning will go away if you remove the blank line above the header. Rules are applied after the YAML front-matter gets removed, so your sample looks like it begins with a blank line.

There's an exception for the following, but because HTML comments aren't treated the same as YAML:

```md
<!-- markdownlint-disable no-hard-tabs -->

# Heading
```

Do you think the same exception should apply?

**Comment by unional** [comment]
Got it. Thanks!
